const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  personalGroupID: state => state.user.personalGroupID,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  // searchParams: state => state.resources.searchParams,
  // isSearch: state => state.resources.isSearch,
  account: state => state.user.account,
  resources: state => state.resources,
  myParams: state => state.resources.myParams,
  reload: state => state.tagsView.reload,
  memberId: state => state.user.memberId,
  isAdmin: state => state.user.isAdmin,
  newReceiveCount: state => state.user.newReceiveCount,
  groupId: state => state.resources.groupId,
  pageNum: state => state.resources.pageNum,
  // office's state
  mode: state => state.office.mode,
  type: state => state.office.type,
  documentType: state => state.office.documentType,
  document: state => state.office.document,
  editorConfig: state => state.office.editorConfig,
}

export default getters
